appli/urls.py
from django.urls import path
from . import views

app_name = "appli"
urlpatterns = [
    path("", views.index, name="index"), 
    path("show", views.show, name="show"),
    path("<str:name>", views.random, name="random")
]

django_lab/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appli/', include("appli.urls")),
    path('new_year/', include("new_year.urls")),
    path('taskform/', include("taskform.urls")),
    path('tasks/', include("tasks.urls"))
]

new_year/urls.py
from . import views
from django.urls import path

app_name = "new_year"
urlpatterns = [
    # this url
    path('', views.newyear, name="newyear"),
    path('extending', views.extending, name="extending")
]

taskform/urls.py
from django.urls import path
from . import views

app_name = "taskform"

urlpatterns = [
    path("", views.tasks, name = "tasks"),
    path("mainform", views.mainform, name = "mainform")
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name = "index"),
    path("add", views.add, name = "add")
]

tasks/models.py
from django.db import models

# Create your models here.

appli/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "appli/index.html")

def show(request):
    return HttpResponse("Show method")

def random(request, name):
    return render(request, "appli/random.html", {
        "name" : name.capitalize()
    })

new_year/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime

# Create your views here.

def newyear(request):
    date = datetime.datetime.now()

    return render(request, "new_year/newyear.html", {
        "ans" : date.month == 1 and date.day == 1,
        "date" : date
    })

def extending(request):
    return render(request, "new_year/extending.html")

taskform/views.py
from django.shortcuts import render
from django import forms

tasks = []

class NewTaskForm(forms.Form):
    taskname = forms.CharField(label="Task Name")
    # priority = forms.IntegerField(label="Priority", max_value=10, min_value=2)

# Create your views here.
def mainform(request):
    if request.method=="POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data("taskname")
            tasks.append(task)
            return render(request, "taskform/tasks.html")
        else:
            return render(request, "taskform/tasks.html", {
                "form" : form
            })

    return render(request, "taskform/dataform.html", {
        "form" : NewTaskForm()
    })

def tasks(request, tasks):
    return render(request, "taskform/tasks.html", {
        "tasks" : tasks
    })

tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="Task Name")

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks" : request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session['tasks'] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form" : form
            })
    
    return render(request, "tasks/add.html", {
        "form" : NewTaskForm()
    })

appli/templates/appli/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <h1>Hello Index Method of Appli application, I'm a template index.html executed in you!!</h1>
</body>
</html>

appli/templates/appli/random.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Random</title>
</head>
<body>
    <h1>Hello {{name}}</h1>
</body>
</html>

new_year/templates/new_year/extending.html
{% extends 'new_year/layout.html' %}

{% block body %}
<h1>This template is made by extending the layout.html file</h1>
 <!-- the url will search a name='newyear' from the file urls.py -->
<a href="{% url 'new_year:newyear' %}">Is today New Year?</a> <br>
<a href="{% url 'appli:index' %}">Click to visit index of application named Appli</a>
{% endblock %}

new_year/templates/new_year/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'new_year/styles.css'%}">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

new_year/templates/new_year/newyear.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'new_year/styles.css' %}" rel="stylesheet">
    <title>New Year</title>
</head>
<body>
    <h1>{{date}}</h1>
    {% if ans %}
        <h2>Happy New Year</h2>
    {% else %}
        <h2>Today is not new year</h2>
    {% endif %}
</body>
</html>

taskform/templates/taskform/dataform.html
{% extends 'taskform/layout.html' %}

{% block body %}
<h1>Tasks</h1>
    <form action="{% url 'taskform:tasks' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'taskform:tasks' %}">View tasks</a>
{% endblock %}

taskform/templates/taskform/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}

</body>
</html>

taskform/templates/taskform/tasks.html
{% extends 'taskform/layout.html' %}

{% block body %}
    <h1>Tasks:</h1>
    <h2>{{ tasks }}</h2>
    <a href="{% url 'taskform:mainform' %}">Add new task</a>
{% endblock %}

tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block body %}
<h1>Tasks</h1>
    <form action="{% url 'tasks:add' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <h1>Tasks:</h1>
    <ul>
    {% for task in tasks %}
        <li>{{ task }}</li>
    {% empty %}
        <li>No task exists!</li>
    {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add new task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>